#!/bin/bash

n=0
cat gene.bed | while read line
do
#SNP call
	line_arr=( $line )
    	chr="chr"
	name=${line_arr[0]}
	pos=${line_arr[1]}
	sta=${line_arr[2]}
	end=${line_arr[3]}
    echo $name
samtools merge -R ${chr}${pos}:$sta-$end -f ~/gene.bam bam.file.list
samtools mpileup -uf /ucsc.hg19.fasta ~/gene.bam | bcftools call -vm -o ~/gene.vcf
#vcf filter
vcffilter -f "DP > 30 & MQ > 20"  ~/gene.vcf > ~/gene2.vcf
grep -v "INDEL" ~/gene2.vcf > ~/gene3.vcf
grep "0/1:" ~/gene3.vcf > ~/gene4.vcf
    ((n=n+1))
    echo $n
Rscript ASE.R $name $n
rm -f ~/gene.bam
rm -f ~/gene.vcf
rm -f ~/gene2.vcf
rm -f ~/gene3.vcf
rm -f ~/gene4.vcf


done
